# Polluants le plus souvent non conformes
***
_Les parties indispensables à run sont indiquées avec la mention [TO RUN], afin de reproduire les analyses se situant sous ces sections._


**Contexte** :<br>
Quelles sont les catégories de polluants qui ressortent le plus dans les catégories NC0 et NC1? <br>
(cf <https://outline.services.dataforgood.fr/doc/espace-de-travail-data-analysts-Q3VWrKUd2g>)


**Choses à faire** :
- Etudier le nombre de prélèvements en non conformité (dépassent la limite de qualité)
- Etudier la répartition géographique de ces prélèvements non conformes.
    * Quelles sont les communes avec le plus de dépassements? 
    * Dans quelles régions sont elles situées? 
- Certaines catégories de polluants (-> dépend de la tâche catégorisation polluants)

**Plus tard**:
- Etudier les situations de conformité de chaque catégorie de polluants <br> (i.e. C, NC0 ou NC1 cf <<<https://outline.services.dataforgood.fr/doc/espace-de-travail-data-analysts-Q3VWrKUd2g>>>) et leur répartition sur le territoire (échelle de la commune) pour 2024. 
    * Quelle catégorie de polluants a le plus de paramètres avec au moins un NC1? NC0? 
    * Quelles catégories sont les plus conformes? 
    * Au niveau géographiques: quelles régions françaises montrent le plus de situations de non conformité par catégorie de polluants.
- Etendre l'analyse précédente à 2023, 2021 et 2020 et faire un retour sur l'évolution

# Résumé de l'étude
***

**I. Etudier le nombre de prélèvements en non conformité (dépassent la limite de qualité)**

En 2024 sur 416128  prélèvements, 89299  étaient non conforme soit 21.46 % 

**II. Etudier la répartition géographique de ces prélèvements non conformes.**
    
- **1. Quelles sont les communes avec le plus de dépassements?** <br>
On a 2678 communes (soit 7.8 % du total) avec 100% des prélèvements non conformes<br>
Pour la liste complète, voir les détails plus bas

Voici un extrait de 10 :

|             nomcommuneprinc             | inseecommuneprinc | nb_prel_tot | nb_prel_non_conformes | percent_prel_non_conformes |
| --- | --- | --- | --- | --- |
| GROS-MORNE                              | 97212             |         188 |                   188 |                      100.0 |
| SAINT-JOSEPH                            | 97224             |         176 |                   176 |                      100.0 |
| ROBERT (LE)                             | 97222             |         160 |                   160 |                      100.0 |
| FORT-DE-FRANCE                          | 97209             |         159 |                   159 |                      100.0 |
| YSSINGEAUX                              | 43268             |         110 |                   110 |                      100.0 |
| VALLEES-D'ANTRAIGUES-ASPERJOC           | 07011             |          84 |                    84 |                      100.0 |
| AMBERT                                  | 63003             |          82 |                    82 |                      100.0 |
| BOUSSENAC                               | 09065             |          80 |                    80 |                      100.0 |
| VIDAUBAN                                | 83148             |          70 |                    70 |                      100.0 |
| SAINT-LAURENT-LES-BAINS-LAVAL-D'AURELLE | 07262             |          61 |                    61 |                      100.0 |

    
- **2. Dans quelles régions sont elles situées?** 

_Attention_ :  J'ai des prélèvements pour lequels je n'associe pas une région ( NULL voir plus en détails dans l'étude plus bas).

Les 5 régions avec le plus de pourcentage de prélévement non conformes sont
            
| code_region |        name_regions        | nb_prel_tot | nb_prel_non_conformes | percent_prel_non_conformes |
| --- | --- | --- | --- | --- |
|         2.0 | MARTINIQUE                 |        1437 |                  1418 |                      98.68 |
|         3.0 | GUYANE                     |         493 |                   458 |                       92.9 |
|         1.0 | GUADELOUPE                 |        2295 |                  1826 |                      79.56 |
|         4.0 | LA REUNION                 |        3092 |                  2216 |                      71.67 |
|        94.0 | CORSE                      |        4529 |                  2970 |                      65.58 |



**III. Certaines catégories de polluants** (-> dépend de la tâche catégorisation polluants)

Parmis les polluants catégorisés dans "analytics/notebooks/exploration.ipynb"

**CAS A**<br>
A chaque résultat (subtsances), on associe le prélèvement pour indiquer la conformité ou non du prélèvement.
            
|     cat_polluant     | nb_prel_tot | nb_prel_non_conformes | percent_prel_non_conformes_vs_all |
| --- | --- | --- | --- | 
| other                |    17229008 |               5488979 |                             31.86 |
| hydrocarbures        |       99366 |                 42263 |                             42.53 |
| pesticides           |      879998 |                350017 |                             39.77 |
| nitrates et nitrites |      392226 |                 95851 |                             24.44 |
| métaux lourds        |      131941 |                 40710 |                             30.85 |
| phtalates            |         159 |                    51 |                             32.08 |
| PFAS                 |       41389 |                  6896 |                             16.66 |


**CAS B**<br>
Il s'agit de recatégoriser la conformité ou non des prélévements en regardant juste les données associées à la substance étudiée dans le test (!= prélévement).<br>


|     cat_polluant     | nb_prel_tot | nb_prel_non_conformes | percent_prel_non_conformes_vs_all |
| --- | --- | --- | --- | 
| pesticides           |     3046621 |                 27423 |                               0.9 |
| métaux lourds        |      481275 |                 95482 |                             19.84 |
| nitrates et nitrites |     1303547 |                738982 |                             56.69 |
| phtalates            |        1426 |                    55 |                              3.86 |
| other                |    58926728 |              12406245 |                             21.05 |
| PFAS                 |       42488 |                    64 |                              0.15 |
| hydrocarbures        |      362413 |                   524 |                              0.14 |

# Questions ouvertes
***
1. Comment faire le lien commune/région ? Les données INSEE que j'ai pu trouvée laisse encore des lignes avec régions NULL
2. Pour la partie sur les catégories de polluant
    - Refaire l'étude avec la table de mapping données par Pauline
    - Que souhaite-t-on savoir ? Cas A ou Cas B (Cf explication juste la cellule du dessus)?

# Etude
***
### Packages + read data

In [1]:
# [TO RUN]  Packages
import pandas as pd

pd.set_option("display.max_columns", None)  # show all cols
pd.set_option("display.max_colwidth", None)  # show full width of showing cols
pd.set_option(
    "display.expand_frame_repr", False
)  # print cols side by side as it's supposed to be

In [2]:
# [TO RUN]
import duckdb
from pipelines.tasks._common import DUCKDB_FILE

con = duckdb.connect(database=DUCKDB_FILE, read_only=True)

In [3]:
# [TO RUN]  On se concentre sur 2024, on peut modifier la date ici pour plus de data
date_min = "2024-01-01"

###  Exploration

In [4]:
# [OPTIONAL] Tables dispo dans la bdd
con.sql("SHOW TABLES").show()

┌──────────────────┐
│       name       │
│     varchar      │
├──────────────────┤
│ edc_communes     │
│ edc_prelevements │
│ edc_resultats    │
└──────────────────┘

In [5]:
# [OPTIONAL] Preview edc_prelevements
preview_prel = con.sql("SELECT * FROM edc_prelevements LIMIT 2").df()
preview_prel

  cddept   cdreseau inseecommuneprinc nomcommuneprinc cdreseauamont      nomreseauamont pourcentdebit referenceprel   dateprel heureprel                                                                                           conclusionprel                         ugelib                        distrlib                          moalib plvconformitebacterio plvconformitechimique plvconformitereferencebact plvconformitereferencechim  de_partition de_ingestion_date de_dataset_datetime
0    001  001000003             01007        AMBRONAY          None                None          None   00100119766 2020-02-13     11h40  Eau d'alimentation conforme aux exigences de qualité en vigueur pour l'ensemble des paramètres mesurés.  SI REGION D'AMBERIEU-EN-BUGEY  SIE REGION D'AMBERIEU-EN-BUGEY  SIE REGION D'AMBERIEU-EN-BUGEY                     C                     C                          C                          C          2020        2025-02-14     20230811-150005
1    001  001000003             01007        AMBRONAY     001001304  TTP (CLG) AMBRONAY         100 %   00100120290 2020-03-17     11h15  Eau d'alimentation conforme aux exigences de qualité en vigueur pour l'ensemble des paramètres mesurés.  SI REGION D'AMBERIEU-EN-BUGEY  SIE REGION D'AMBERIEU-EN-BUGEY  SIE REGION D'AMBERIEU-EN-BUGEY                     C                     C                          C                          C          2020        2025-02-14     20230811-150005

###  I. Etudier le nombre de prélèvements en non conformité 

**Quels sont les prélévelment qui dépassent la limite de qualité ?**

Dans le document PDF "eau-distrib-documentation"
 
#### 1.2.14 CONFORMITE DU PRELEVEMENT
La conformité du prélèvement est définie par rapport à deux types d’exigences de qualité, les limites de qualité et les références de qualité (cf § « les exigences de qualité » dans la partie « Contexte et description des données »), en distinguant pour chaque type d’exigence les paramètres microbiologiques des substances chimiques.

##### 1.2.14.1 plvconformitebacterio
Indicateur de la conformité des paramètres microbiologiques aux limites de qualité en vigueur au moment du prélèvement pour le type d’eau considéré.
Valeurs possibles : "blanc", "C=conforme", "N=non conforme", "S (sans objet lorsqu'aucun paramètre microbio n'a été mesuré)".

##### 1.2.14.2 plvconformitechimique
Indicateur de la conformité des paramètres chimiques aux limites de qualité en vigueur au moment du prélèvement pour le type d’eau considéré (et en prenant en compte les dérogations éventuelles en cours pour l'installation concernée).
Valeurs possibles : "blanc", "C=conforme", "N=non conforme", "D=conforme dans le cadre d’une dérogation","S (sans objet lorsqu'aucun paramètre chimique n'a été mesuré)".

##### 1.2.14.2.1 plvconformitereferencebact
Indicateur de la conformité des paramètres microbiologiques aux références de qualité en vigueur au moment du prélèvement pour le type d’eau considéré.
Valeurs possibles : "blanc", "C=conforme", "N=non conforme", "S (sans objet lorsqu'aucun paramètre microbio n'a été mesuré)".

##### 1.2.14.3 plvconformitereferencechim
Indicateur de la conformité des paramètres chimiques aux références de qualité en vigueur au moment du prélèvement pour le type d’eau considéré.
Valeurs possibles : "blanc", "C=conforme", "N=non conforme", "S (sans objet lorsqu'aucun paramètre chimique n'a été mesuré)".

In [6]:
# [TO RUN] Compter les prélévements non conformes en 2024
query_2024_count_conformity = f"""
SELECT
  COUNT(*) AS nb_prel_tot,
  SUM(CASE 
        WHEN ("plvconformitebacterio" = 'N' OR  "plvconformitechimique" = 'N' OR  "plvconformitereferencebact" = 'N' OR  "plvconformitereferencechim" = 'N' )
        THEN 1 ELSE 0 END ) AS nb_prel_non_conformes,
  ROUND(SUM(CASE 
        WHEN ("plvconformitebacterio" = 'N' OR  "plvconformitechimique" = 'N' OR  "plvconformitereferencebact" = 'N' OR  "plvconformitereferencechim" = 'N' )
        THEN 1 ELSE 0  END )/ COUNT(*) 
        * 100,
        2) AS percent_prel_non_conformes_vs_all,
FROM edc_prelevements
WHERE
  dateprel >= '{date_min}'
"""

con.sql(query_2024_count_conformity).show()

┌─────────────┬───────────────────────┬───────────────────────────────────┐
│ nb_prel_tot │ nb_prel_non_conformes │ percent_prel_non_conformes_vs_all │
│    int64    │        int128         │              double               │
├─────────────┼───────────────────────┼───────────────────────────────────┤
│      416128 │                 89299 │                             21.46 │
└─────────────┴───────────────────────┴───────────────────────────────────┘

###  II. Etudier la répartition géographique de ces prélèvements non conformes.

#### 1. Quelles sont les communes avec le plus de dépassements? 

Dans le document PDF "eau-distrib-documentation"

**1.2.2 INSEECOMMUNEPRINC**<br>
Code INSEE de la commune où se trouve le point de surveillance sur lequel le prélèvement a eu lieu.

**1.2.3 NOMCOMMUNEPRINC**<br>
Nom de la commune où se trouve le point de surveillance sur lequel le prélèvement a eu lieu.

In [7]:
#  [TO RUN] Répartir les prélévements non conformes en 2024 par communes

query_2024_count_conformity_by_com = f"""
SELECT
  NOMCOMMUNEPRINC, 
  INSEECOMMUNEPRINC,
  COUNT(*) AS nb_prel_tot,
  SUM(CASE 
        WHEN ("plvconformitebacterio" = 'N' OR  "plvconformitechimique" = 'N' OR  "plvconformitereferencebact" = 'N' OR  "plvconformitereferencechim" = 'N' )
        THEN 1 ELSE 0 END ) AS nb_prel_non_conformes,
  ROUND(SUM(CASE 
        WHEN ("plvconformitebacterio" = 'N' OR  "plvconformitechimique" = 'N' OR  "plvconformitereferencebact" = 'N' OR  "plvconformitereferencechim" = 'N' )
        THEN 1 ELSE 0  END )/ COUNT(*) 
        * 100,
        2) AS percent_prel_non_conformes
FROM edc_prelevements
WHERE
  dateprel >= '{date_min}'
GROUP BY 
   NOMCOMMUNEPRINC, 
   INSEECOMMUNEPRINC
ORDER BY 
   percent_prel_non_conformes DESC,
   nb_prel_non_conformes  DESC
"""

con.sql(query_2024_count_conformity_by_com).show()

┌─────────────────────────────────────────┬───────────────────┬─────────────┬───────────────────────┬────────────────────────────┐
│             nomcommuneprinc             │ inseecommuneprinc │ nb_prel_tot │ nb_prel_non_conformes │ percent_prel_non_conformes │
│                 varchar                 │      varchar      │    int64    │        int128         │           double           │
├─────────────────────────────────────────┼───────────────────┼─────────────┼───────────────────────┼────────────────────────────┤
│ GROS-MORNE                              │ 97212             │         188 │                   188 │                      100.0 │
│ SAINT-JOSEPH                            │ 97224             │         176 │                   176 │                      100.0 │
│ ROBERT (LE)                             │ 97222             │         160 │                   160 │                      100.0 │
│ FORT-DE-FRANCE                          │ 97209             │         159 │                   159 │                      100.0 │
│ YSSINGEAUX                              │ 43268             │         110 │                   110 │                      100.0 │
│ VALLEES-D'ANTRAIGUES-ASPERJOC           │ 07011             │          84 │                    84 │                      100.0 │
│ AMBERT                                  │ 63003             │          82 │                    82 │                      100.0 │
│ BOUSSENAC                               │ 09065             │          80 │                    80 │                      100.0 │
│ VIDAUBAN                                │ 83148             │          70 │                    70 │                      100.0 │
│ SAINT-LAURENT-LES-BAINS-LAVAL-D'AURELLE │ 07262             │          61 │                    61 │                      100.0 │
│   ·                                     │   ·               │           · │                     · │                         ·  │
│   ·                                     │   ·               │           · │                     · │                         ·  │
│   ·                                     │   ·               │           · │                     · │                         ·  │
│ AUDRIX                                  │ 24015             │           5 │                     1 │                       20.0 │
│ NEUVILLE-SAINT-VAAST                    │ 62609             │           5 │                     1 │                       20.0 │
│ GERMIGNY-DES-PRES                       │ 45153             │           5 │                     1 │                       20.0 │
│ SAINT-MARTIN-DE-PALLIERES               │ 83114             │           5 │                     1 │                       20.0 │
│ VIOLES                                  │ 84149             │           5 │                     1 │                       20.0 │
│ BAREN                                   │ 31046             │           5 │                     1 │                       20.0 │
│ MAGNY-SUR-TILLE                         │ 21370             │           5 │                     1 │                       20.0 │
│ ORGEUX                                  │ 21469             │           5 │                     1 │                       20.0 │
│ MIGE                                    │ 89256             │           5 │                     1 │                       20.0 │
│ ETALANTE                                │ 21253             │           5 │                     1 │                       20.0 │
├─────────────────────────────────────────┴───────────────────┴─────────────┴───────────────────────┴────────────────────────────┤
│ ? rows (>9999 rows, 20 shown)                                                                                        5 columns │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [8]:
#  [TO RUN] Répartir les prélévements non conformes en 2024 par commune

query_2024_conformity_com_repartition = f"""
WITH COMMUNES AS (
    {query_2024_count_conformity_by_com}
    ),
    
    TOTAL AS (
    SELECT
        COUNT(INSEECOMMUNEPRINC) AS tot_commune
    FROM
        COMMUNES
    )
    
SELECT
    (CASE WHEN percent_prel_non_conformes = 100 THEN '100%'
         WHEN percent_prel_non_conformes <10 THEN '0-10%'
         WHEN percent_prel_non_conformes <20 THEN '11-20%'
         WHEN percent_prel_non_conformes <30 THEN '21-30%'
         WHEN percent_prel_non_conformes <40 THEN '31-40%'
         WHEN percent_prel_non_conformes <50 THEN '41-50%'
         WHEN percent_prel_non_conformes <60 THEN '51-60%'
         WHEN percent_prel_non_conformes <70 THEN '61-70%'
         WHEN percent_prel_non_conformes <80 THEN '71-80%'
         WHEN percent_prel_non_conformes <90 THEN '81-90%'
         WHEN percent_prel_non_conformes <100 THEN '91-99%'
         END) AS percent_prel_non_conformes_cat, 
    COUNT(INSEECOMMUNEPRINC) AS nb_communes,
    MAX(tot_commune) AS tot_commune,
    ROUND(COUNT(INSEECOMMUNEPRINC)/MAX(tot_commune) *100,2) AS percent_communes
FROM
    COMMUNES
CROSS JOIN 
    TOTAL
GROUP BY
    percent_prel_non_conformes_cat
ORDER BY 
    percent_prel_non_conformes_cat
"""

con.sql(query_2024_conformity_com_repartition).show()

┌────────────────────────────────┬─────────────┬─────────────┬──────────────────┐
│ percent_prel_non_conformes_cat │ nb_communes │ tot_commune │ percent_communes │
│            varchar             │    int64    │    int64    │      double      │
├────────────────────────────────┼─────────────┼─────────────┼──────────────────┤
│ 0-10%                          │       21747 │       34349 │            63.31 │
│ 100%                           │        2678 │       34349 │              7.8 │
│ 11-20%                         │        2548 │       34349 │             7.42 │
│ 21-30%                         │        2110 │       34349 │             6.14 │
│ 31-40%                         │        1370 │       34349 │             3.99 │
│ 41-50%                         │         797 │       34349 │             2.32 │
│ 51-60%                         │        1217 │       34349 │             3.54 │
│ 61-70%                         │         579 │       34349 │             1.69 │
│ 71-80%                         │         411 │       34349 │              1.2 │
│ 81-90%                         │         549 │       34349 │              1.6 │
│ 91-99%                         │         343 │       34349 │              1.0 │
├────────────────────────────────┴─────────────┴─────────────┴──────────────────┤
│ 11 rows                                                             4 columns │
└───────────────────────────────────────────────────────────────────────────────┘

####  2. Dans quelles régions sont elles situées?

Pour relier les communes au niveau region, je vais utiliser les données disponible ici : https://www.insee.fr/fr/information/7766585

In [9]:
# [TO RUN] Table de correspondance maintenue par INSEE
url = "https://www.insee.fr/fr/statistiques/fichier/7766585/v_commune_2024.csv"
geo = pd.read_csv(url)

geo.head()

  TYPECOM    COM   REG DEP CTCD  ARR  TNCC                    NCC                 NCCENR                  LIBELLE   CAN  COMPARENT
0     COM  01001  84.0  01  01D  012     5  ABERGEMENT CLEMENCIAT  Abergement-Clémenciat  L'Abergement-Clémenciat  0108        NaN
1     COM  01002  84.0  01  01D  011     5    ABERGEMENT DE VAREY    Abergement-de-Varey    L'Abergement-de-Varey  0101        NaN
2     COM  01004  84.0  01  01D  011     1      AMBERIEU EN BUGEY      Ambérieu-en-Bugey        Ambérieu-en-Bugey  0101        NaN
3     COM  01005  84.0  01  01D  012     1    AMBERIEUX EN DOMBES    Ambérieux-en-Dombes      Ambérieux-en-Dombes  0122        NaN
4     COM  01006  84.0  01  01D  011     1                AMBLEON                Ambléon                  Ambléon  0104        NaN

In [10]:
# [TO RUN] Add new table TEMPORAIRE to JOIN (pas de droit d'écriture)
con.sql("CREATE TEMP VIEW regions AS SELECT * FROM geo")

In [11]:
# [OPTIONAL] Preview regions
preview_regions = con.sql("SELECT * FROM regions LIMIT 5").df()
preview_regions

  TYPECOM    COM   REG DEP CTCD  ARR  TNCC                    NCC                 NCCENR                  LIBELLE   CAN  COMPARENT
0     COM  01001  84.0  01  01D  012     5  ABERGEMENT CLEMENCIAT  Abergement-Clémenciat  L'Abergement-Clémenciat  0108        NaN
1     COM  01002  84.0  01  01D  011     5    ABERGEMENT DE VAREY    Abergement-de-Varey    L'Abergement-de-Varey  0101        NaN
2     COM  01004  84.0  01  01D  011     1      AMBERIEU EN BUGEY      Ambérieu-en-Bugey        Ambérieu-en-Bugey  0101        NaN
3     COM  01005  84.0  01  01D  012     1    AMBERIEUX EN DOMBES    Ambérieux-en-Dombes      Ambérieux-en-Dombes  0122        NaN
4     COM  01006  84.0  01  01D  011     1                AMBLEON                Ambléon                  Ambléon  0104        NaN

In [12]:
# [TO RUN] Ajoutons également les noms de régions
url2 = "https://www.insee.fr/fr/statistiques/fichier/7766585/v_region_2024.csv"
region_name = pd.read_csv(url2)
con.sql("CREATE TEMP VIEW name_regions AS SELECT * FROM region_name")

In [13]:
# [OPTIONAL] Preview name_regions
preview_name_regions = con.sql("SELECT * FROM name_regions LIMIT 5").df()
preview_name_regions

   REG CHEFLIEU  TNCC         NCC      NCCENR     LIBELLE
0    1    97105     3  GUADELOUPE  Guadeloupe  Guadeloupe
1    2    97209     3  MARTINIQUE  Martinique  Martinique
2    3    97302     3      GUYANE      Guyane      Guyane
3    4    97411     0  LA REUNION  La Réunion  La Réunion
4    6    97611     0     MAYOTTE     Mayotte     Mayotte

In [14]:
# [TO RUN] table de correspondance pour les régions
# On fait un max sur REG car on peut avoir plusieurs ligne par com avec REG null ou non

query_REGION_INFO = """
    SELECT
          regions.COM AS COM,
          name_regions.NCC AS NCC ,
          MAX(regions.REG) AS REG,
    FROM
        regions
    LEFT JOIN 
        name_regions
    ON
        regions.REG = name_regions.REG
    GROUP BY
        1,2
"""

con.sql(query_REGION_INFO).show()

┌─────────┬──────────────────────┬────────┐
│   COM   │         NCC          │  REG   │
│ varchar │       varchar        │ double │
├─────────┼──────────────────────┼────────┤
│ 01001   │ AUVERGNE RHONE ALPES │   84.0 │
│ 01014   │ AUVERGNE RHONE ALPES │   84.0 │
│ 01025   │ AUVERGNE RHONE ALPES │   84.0 │
│ 01026   │ AUVERGNE RHONE ALPES │   84.0 │
│ 01035   │ AUVERGNE RHONE ALPES │   84.0 │
│ 01040   │ AUVERGNE RHONE ALPES │   84.0 │
│ 01046   │ AUVERGNE RHONE ALPES │   84.0 │
│ 01047   │ AUVERGNE RHONE ALPES │   84.0 │
│ 01052   │ AUVERGNE RHONE ALPES │   84.0 │
│ 01053   │ AUVERGNE RHONE ALPES │   84.0 │
│   ·     │  ·                   │     ·  │
│   ·     │  ·                   │     ·  │
│   ·     │  ·                   │     ·  │
│ 35282   │ NULL                 │   NULL │
│ 35293   │ NULL                 │   NULL │
│ 35344   │ NULL                 │   NULL │
│ 58091   │ NULL                 │   NULL │
│ 59248   │ NULL                 │   NULL │
│ 60096   │ NULL                 │   NULL │
│ 60196   │ NULL                 │   NULL │
│ 60245   │ NULL                 │   NULL │
│ 60256   │ NULL                 │   NULL │
│ 91390   │ NULL                 │   NULL │
├─────────┴──────────────────────┴────────┤
│      ? rows (>9999 rows, 20 shown)      │
└─────────────────────────────────────────┘

In [15]:
# [TO RUN] Répartir les prélévements non conformes en 2024 par regions

query_2024_count_conformity_by_reg = f"""
WITH 
REGION_INFO AS (
    {query_REGION_INFO}
)
SELECT
  REGION_INFO.REG AS code_region,
  REGION_INFO.NCC AS name_region ,
  COUNT(*) AS nb_prel_tot,
  SUM(CASE 
        WHEN ("plvconformitebacterio" = 'N' OR  "plvconformitechimique" = 'N' OR  "plvconformitereferencebact" = 'N' OR  "plvconformitereferencechim" = 'N' )
        THEN 1 ELSE 0 END ) AS nb_prel_non_conformes,
  ROUND(SUM(CASE 
        WHEN ("plvconformitebacterio" = 'N' OR  "plvconformitechimique" = 'N' OR  "plvconformitereferencebact" = 'N' OR  "plvconformitereferencechim" = 'N' )
        THEN 1 ELSE 0  END )/ COUNT(*) 
        * 100,
        2) AS percent_prel_non_conformes
FROM 
    edc_prelevements
LEFT JOIN 
    REGION_INFO
ON
    REGION_INFO.COM = edc_prelevements.inseecommuneprinc
WHERE
  dateprel >= '{date_min}'
GROUP BY 
   REGION_INFO.REG,
   REGION_INFO.NCC
ORDER BY 
   percent_prel_non_conformes DESC,
   nb_prel_non_conformes  DESC
"""

con.sql(query_2024_count_conformity_by_reg).show()

┌─────────────┬────────────────────────────┬─────────────┬───────────────────────┬────────────────────────────┐
│ code_region │        name_region         │ nb_prel_tot │ nb_prel_non_conformes │ percent_prel_non_conformes │
│   double    │          varchar           │    int64    │        int128         │           double           │
├─────────────┼────────────────────────────┼─────────────┼───────────────────────┼────────────────────────────┤
│         2.0 │ MARTINIQUE                 │        1437 │                  1418 │                      98.68 │
│         3.0 │ GUYANE                     │         493 │                   458 │                       92.9 │
│         1.0 │ GUADELOUPE                 │        2295 │                  1826 │                      79.56 │
│         4.0 │ LA REUNION                 │        3092 │                  2216 │                      71.67 │
│        94.0 │ CORSE                      │        4529 │                  2970 │                      65.58 │
│         6.0 │ MAYOTTE                    │         584 │                   228 │                      39.04 │
│        76.0 │ OCCITANIE                  │       45834 │                 15154 │                      33.06 │
│        84.0 │ AUVERGNE RHONE ALPES       │       65472 │                 20449 │                      31.23 │
│        44.0 │ GRAND EST                  │       44397 │                 10564 │                      23.79 │
│        NULL │ NULL                       │       16015 │                  3450 │                      21.54 │
│        27.0 │ BOURGOGNE FRANCHE COMTE    │       24426 │                  5070 │                      20.76 │
│        75.0 │ NOUVELLE AQUITAINE         │       35880 │                  6942 │                      19.35 │
│        24.0 │ CENTRE VAL DE LOIRE        │       15261 │                  2729 │                      17.88 │
│        32.0 │ HAUTS DE FRANCE            │       32443 │                  5711 │                       17.6 │
│        28.0 │ NORMANDIE                  │       20167 │                  3506 │                      17.38 │
│        93.0 │ PROVENCE ALPES COTE D AZUR │       35336 │                  6026 │                      17.05 │
│        53.0 │ BRETAGNE                   │       19869 │                  1489 │                       7.49 │
│        52.0 │ PAYS DE LA LOIRE           │       26939 │                  1375 │                        5.1 │
│        11.0 │ ILE DE FRANCE              │       37467 │                  1086 │                        2.9 │
├─────────────┴────────────────────────────┴─────────────┴───────────────────────┴────────────────────────────┤
│ 19 rows                                                                                           5 columns │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

<b> /!\ Attention /!\ </b><br>
J'ai des prélèvements pour lequels je n'associe pas une région.<br>
Il faut peut-être une autre source

In [16]:
# [OPTIONAL]
query_check_reg_null = f"""
WITH 
REGION_INFO AS (
    {query_REGION_INFO}
)
SELECT DISTINCT
  REGION_INFO.REG AS code_region,
  REGION_INFO.NCC AS name_region ,
  edc_prelevements.inseecommuneprinc
FROM 
    edc_prelevements
LEFT JOIN 
    REGION_INFO
ON
    REGION_INFO.COM = edc_prelevements.inseecommuneprinc
WHERE
  dateprel >= '{date_min}'
  AND REGION_INFO.REG IS NULL
"""

con.sql(query_check_reg_null).show()

┌─────────────┬─────────────┬───────────────────┐
│ code_region │ name_region │ inseecommuneprinc │
│   double    │   varchar   │      varchar      │
├─────────────┼─────────────┼───────────────────┤
│        NULL │ NULL        │ 79105             │
│        NULL │ NULL        │ 79196             │
│        NULL │ NULL        │ 79061             │
│        NULL │ NULL        │ 80485             │
│        NULL │ NULL        │ 85009             │
│        NULL │ NULL        │ 85197             │
│        NULL │ NULL        │ 85001             │
│        NULL │ NULL        │ 85090             │
│        NULL │ NULL        │ 85302             │
│        NULL │ NULL        │ 86247             │
│          ·  │  ·          │   ·               │
│          ·  │  ·          │   ·               │
│          ·  │  ·          │   ·               │
│        NULL │ NULL        │ 02439             │
│        NULL │ NULL        │ 03168             │
│        NULL │ NULL        │ 09056             │
│        NULL │ NULL        │ 11131             │
│        NULL │ NULL        │ 16082             │
│        NULL │ NULL        │ 16186             │
│        NULL │ NULL        │ 16097             │
│        NULL │ NULL        │ 16153             │
│        NULL │ NULL        │ 19123             │
│        NULL │ NULL        │ 21352             │
├─────────────┴─────────────┴───────────────────┤
│ 580 rows (20 shown)                 3 columns │
└───────────────────────────────────────────────┘

In [17]:
# [OPTIONAL] On peut avoir plusieurs lignes par numéro de commune ce qui est un problème si on joint ensuite.
query_check_reg = """
SELECT DISTINCT
    COM  , REG ,NCC     
FROM 
    regions
WHERE
    COM IN ('85090','91390','91222')
ORDER BY 
    COM
"""

con.sql(query_check_reg).show()

┌─────────┬────────┬─────────────┐
│   COM   │  REG   │     NCC     │
│ varchar │ double │   varchar   │
├─────────┼────────┼─────────────┤
│ 85090   │   52.0 │ SEVREMONT   │
│ 85090   │   NULL │ FLOCELLIERE │
│ 91222   │   NULL │ ESTOUCHES   │
│ 91390   │   NULL │ MEREVILLE   │
│ 91390   │   11.0 │ MEREVILLOIS │
└─────────┴────────┴─────────────┘

In [18]:
# [OPTIONAL] A-t-on des régions NULL dans le fichier de correspondance ? Oui, 2564 rows
query_check_reg = """
SELECT DISTINCT
    COM  , REG ,NCC     
FROM 
    regions
WHERE
    REG IS NULL
"""

con.sql(query_check_reg).show()

┌─────────┬────────┬──────────────────────────┐
│   COM   │  REG   │           NCC            │
│ varchar │ double │         varchar          │
├─────────┼────────┼──────────────────────────┤
│ 01025   │   NULL │ BAGE LA VILLE            │
│ 01033   │   NULL │ BELLEGARDE SUR VALSERINE │
│ 01039   │   NULL │ BEON                     │
│ 01080   │   NULL │ CHAMPDOR                 │
│ 01091   │   NULL │ CHATILLON EN MICHAILLE   │
│ 01154   │   NULL │ ETREZ                    │
│ 01182   │   NULL │ GROSLEE                  │
│ 01204   │   NULL │ LALLEYRIAT               │
│ 01218   │   NULL │ LOCHIEU                  │
│ 01221   │   NULL │ LOMPNIEU                 │
│   ·     │     ·  │    ·                     │
│   ·     │     ·  │    ·                     │
│   ·     │     ·  │    ·                     │
│ 35257   │   NULL │ SAINT BRICE EN COGLES    │
│ 35282   │   NULL │ SAINT JEAN SUR COUESNON  │
│ 35308   │   NULL │ SAINT PIERRE DE PLESGUEN │
│ 35323   │   NULL │ SELLE EN COGLES          │
│ 35341   │   NULL │ TREMBLAY                 │
│ 57157   │   NULL │ COUTURES                 │
│ 58167   │   NULL │ MICHAUGUES               │
│ 59404   │   NULL │ MOERES                   │
│ 59540   │   NULL │ SAINT POL SUR MER        │
│ 60038   │   NULL │ BACHIVILLERS             │
├─────────┴────────┴──────────────────────────┤
│ 2564 rows (20 shown)              3 columns │
└─────────────────────────────────────────────┘

In [19]:
# [OPTIONAL] Est-ce que toutes les lignes REG NULL sont des doublons ? Non
query_check_reg = """
WITH 
REG_NULL AS (
    SELECT DISTINCT
        COM    
    FROM 
        regions
    WHERE
        REG IS NULL
    )
    
SELECT DISTINCT
    regions.COM , COUNT(*) AS nb
FROM 
    regions
INNER JOIN
    REG_NULL
ON 
    REG_NULL.COM = regions.COM    
GROUP BY
    1
ORDER BY
    regions.COM
"""

con.sql(query_check_reg).show()

┌─────────┬───────┐
│   COM   │  nb   │
│ varchar │ int64 │
├─────────┼───────┤
│ 01015   │     2 │
│ 01025   │     2 │
│ 01033   │     2 │
│ 01036   │     2 │
│ 01039   │     1 │
│ 01059   │     1 │
│ 01080   │     2 │
│ 01091   │     1 │
│ 01097   │     1 │
│ 01119   │     1 │
│   ·     │     · │
│   ·     │     · │
│   ·     │     · │
│ 89429   │     1 │
│ 89435   │     1 │
│ 89448   │     1 │
│ 89454   │     1 │
│ 89457   │     1 │
│ 89473   │     1 │
│ 89476   │     1 │
│ 89484   │     1 │
│ 91222   │     1 │
│ 91390   │     2 │
├─────────┴───────┤
│    2564 rows    │
│   (20 shown)    │
└─────────────────┘

In [20]:
# [TO RUN] Répartir les prélévements non conformes en 2024 par region

query_2024_conformity_reg_repartition = f"""
WITH REG AS (
    SELECT
      regions.REG AS REGION,
      COUNT(*) AS nb_prel_tot,
      SUM(CASE 
            WHEN ("plvconformitebacterio" = 'N' OR  "plvconformitechimique" = 'N' OR  "plvconformitereferencebact" = 'N' OR  "plvconformitereferencechim" = 'N' )
            THEN 1 ELSE 0 END ) AS nb_prel_non_conformes,
      ROUND(SUM(CASE 
            WHEN ("plvconformitebacterio" = 'N' OR  "plvconformitechimique" = 'N' OR  "plvconformitereferencebact" = 'N' OR  "plvconformitereferencechim" = 'N' )
            THEN 1 ELSE 0  END )/ COUNT(*) 
            * 100,
            2) AS percent_prel_non_conformes
    FROM 
        edc_prelevements
    LEFT JOIN 
        regions
    ON
        regions.COM = edc_prelevements.inseecommuneprinc
    WHERE
      dateprel >= '{date_min}'
    GROUP BY 
       regions.REG
    ),
    
    TOTAL AS (
    SELECT
        COUNT(REGION) AS tot_region
    FROM
        REG
    )
    
SELECT
    (CASE WHEN percent_prel_non_conformes = 100 THEN '100%'
         WHEN percent_prel_non_conformes <10 THEN '0-10%'
         WHEN percent_prel_non_conformes <20 THEN '11-20%'
         WHEN percent_prel_non_conformes <30 THEN '21-30%'
         WHEN percent_prel_non_conformes <40 THEN '31-40%'
         WHEN percent_prel_non_conformes <50 THEN '41-50%'
         WHEN percent_prel_non_conformes <60 THEN '51-60%'
         WHEN percent_prel_non_conformes <70 THEN '61-70%'
         WHEN percent_prel_non_conformes <80 THEN '71-80%'
         WHEN percent_prel_non_conformes <90 THEN '81-90%'
         WHEN percent_prel_non_conformes <100 THEN '91-99%'
         END) AS percent_prel_non_conformes_cat, 
    COUNT(REGION) AS nb_regions,
    MAX(tot_region) AS tot_region,
    ROUND(COUNT(REGION)/MAX(tot_region) *100,2) AS percent_regions
FROM
    REG
CROSS JOIN 
    TOTAL
GROUP BY
    percent_prel_non_conformes_cat
ORDER BY 
    percent_prel_non_conformes_cat
"""

con.sql(query_2024_conformity_reg_repartition).show()

┌────────────────────────────────┬────────────┬────────────┬─────────────────┐
│ percent_prel_non_conformes_cat │ nb_regions │ tot_region │ percent_regions │
│            varchar             │   int64    │   int64    │     double      │
├────────────────────────────────┼────────────┼────────────┼─────────────────┤
│ 0-10%                          │          3 │         18 │           16.67 │
│ 11-20%                         │          5 │         18 │           27.78 │
│ 21-30%                         │          2 │         18 │           11.11 │
│ 31-40%                         │          3 │         18 │           16.67 │
│ 61-70%                         │          1 │         18 │            5.56 │
│ 71-80%                         │          2 │         18 │           11.11 │
│ 91-99%                         │          2 │         18 │           11.11 │
└────────────────────────────────┴────────────┴────────────┴─────────────────┘

### III. Certaines catégories de polluants (-> dépend de la tâche catégorisation polluants)

Je reprends la catégorisation faite dans "analytics/notebooks/exploration.ipynb"

            # Filtrage des substances par recherche texte
            categories_polluants = {
                "pesticides": ["azine", "phos", "triazine", "glyphosate", "atrazine", "metolachlor"],
                "nitrates et nitrites": ["nitrate", "nitrite"],
                "PFAS": ["fluoro", "perfluoro", "PFOA", "PFOS"],
                "phtalates": ["phtalate", "DEHP", "BBP", "DBP"],
                "chlorure de vinyle": ["chlorure de vinyle"],
                "hydrocarbures": ["benzène", "toluène", "naphtalène", "xylène"],
                "métaux lourds": ["mercure", "plomb", "arsenic", "cadmium", "nickel", "chrome"],
            }

Et je l'applique en SQL avec un CASE WHEN 

On doit utiliser la table résultat pour regarder les données des prélèvements par substance (champ `libmajparametre`)

**CAS A**
A chaque résultat (subtsances), on associe le prélèvement pour indiquer la conformité ou non du prélèvement.

**CAS B**
Il s'agit de recatégoriser la conformité ou non des prélévements en regardant juste les données associées à la substance étudiées dans le test

In [21]:
# [OPTIONAL] Preview edc_resultats
preview_resultats = con.sql("SELECT * FROM edc_resultats LIMIT 2").df()
preview_resultats

  cddept referenceprel cdparametresiseeaux  cdparametre     libmajparametre     libminparametre libwebparametre qualitparam insituana   rqana cdunitereferencesiseeaux cdunitereference  limitequal refqual  valtraduite   casparam referenceanl  de_partition de_ingestion_date de_dataset_datetime
0    001   00100119085              12DCLE         1161  DICHLOROÉTHANE-1,2  Dichloroéthane-1,2            None           N         L   <0,50                     µg/L              133    <=3 µg/L    None          0.0   107-06-2  00100125759          2020        2025-02-14     20230811-150005
1    001   00100119085                 A2H         1832  ATRAZINE-2-HYDROXY  Atrazine-2-hydroxy            None           N         L  <0,020                     µg/L              133  <=0,1 µg/L    None          0.0  2163-68-0  00100125759          2020        2025-02-14     20230811-150005

##### CAS A

In [22]:
# [TO RUN]

query_polluant = """ 
SELECT
  referenceprel,
  libmajparametre,
  (CASE
    WHEN
        (LOWER(libmajparametre) LIKE '%azine%' OR
        LOWER(libmajparametre) LIKE '%phos%' OR
        LOWER(libmajparametre) LIKE '%triazine%' OR
        LOWER(libmajparametre) LIKE '%glyphosate%' OR
        LOWER(libmajparametre) LIKE '%atrazine%' OR
        LOWER(libmajparametre) LIKE '%metolachlor%') THEN 'pesticides'
    WHEN
        (LOWER(libmajparametre) LIKE '%nitrate%' OR
        LOWER(libmajparametre) LIKE '%nitrite%') THEN 'nitrates et nitrites'
    WHEN
        (LOWER(libmajparametre) LIKE '%fluoro%' OR
        LOWER(libmajparametre) LIKE '%perfluoro%' OR
        LOWER(libmajparametre) LIKE '%pfoa%' OR
        LOWER(libmajparametre) LIKE '%pfos%') THEN 'PFAS'
    WHEN
        (LOWER(libmajparametre) LIKE '%phtalate%' OR
        LOWER(libmajparametre) LIKE '%dehp%' OR
        LOWER(libmajparametre) LIKE '%bbp%' OR
        LOWER(libmajparametre) LIKE '%dbp%') THEN 'phtalates'
    WHEN
        libmajparametre = 'chlorure de vinyle' THEN 'chlorure de vinyle'
    WHEN
        (LOWER(libmajparametre) LIKE '%benzène%' OR
        LOWER(libmajparametre) LIKE '%toluène%' OR
        LOWER(libmajparametre) LIKE '%naphtalène%' OR
        LOWER(libmajparametre) LIKE '%xylène%') THEN 'hydrocarbures'
    WHEN
        (LOWER(libmajparametre) LIKE '%mercure%' OR
        LOWER(libmajparametre) LIKE '%plomb%' OR
        LOWER(libmajparametre) LIKE '%arsenic%' OR
        LOWER(libmajparametre) LIKE '%cadmium%' OR
        LOWER(libmajparametre) LIKE '%nickel%' OR
        LOWER(libmajparametre) LIKE '%chrome%') THEN 'métaux lourds'
    ELSE 'other'
  END ) AS cat_polluant
FROM  
    edc_resultats 
"""

con.sql(query_polluant).show()

┌───────────────┬─────────────────────────────────────┬──────────────┐
│ referenceprel │           libmajparametre           │ cat_polluant │
│    varchar    │               varchar               │   varchar    │
├───────────────┼─────────────────────────────────────┼──────────────┤
│ 00100119085   │ DICHLOROÉTHANE-1,2                  │ other        │
│ 00100119085   │ ATRAZINE-2-HYDROXY                  │ pesticides   │
│ 00100119085   │ ACRYLAMIDE                          │ other        │
│ 00100119085   │ ACTIVITÉ BÊTA ATTRIBUABLE AU K40    │ other        │
│ 00100119085   │ ACTIVITÉ TRITIUM (3H)               │ other        │
│ 00100119085   │ ATRAZINE DÉSÉTHYL                   │ pesticides   │
│ 00100119085   │ ATRAZINE DÉSÉTHYL-2-HYDROXY         │ pesticides   │
│ 00100119085   │ ATRAZINE DÉSÉTHYL DÉISOPROPYL       │ pesticides   │
│ 00100119085   │ ATRAZINE-DÉISOPROPYL                │ pesticides   │
│ 00100119085   │ ALUMINIUM TOTAL µG/L                │ other        │
│      ·        │    ·                                │   ·          │
│      ·        │    ·                                │   ·          │
│      ·        │    ·                                │   ·          │
│ 00100119846   │ BROMACIL                            │ other        │
│ 00100119846   │ BROMADIOLONE                        │ other        │
│ 00100119846   │ BROMOPHOS ÉTHYL                     │ pesticides   │
│ 00100119846   │ BROMOPHOS MÉTHYL                    │ pesticides   │
│ 00100119846   │ BROMOPROPYLATE                      │ other        │
│ 00100119846   │ BROMOXYNIL                          │ other        │
│ 00100119846   │ BACT. ET SPORES SULFITO-RÉDU./100ML │ other        │
│ 00100119846   │ BUTURON                             │ other        │
│ 00100119846   │ BITERTANOL                          │ other        │
│ 00100119846   │ BENTAZONE                           │ other        │
├───────────────┴─────────────────────────────────────┴──────────────┤
│ ? rows (>9999 rows, 20 shown)                            3 columns │
└────────────────────────────────────────────────────────────────────┘

In [23]:
# [TO RUN] Compter les prélévements non conformes en 2024 par catégorire de polluants

query_2024_count_conformity_cat = f"""
WITH
    RESULTATS AS (
        {query_polluant}
    ),

    PRELEVEMENTS AS (
        SELECT DISTINCT
            referenceprel,
            (CASE WHEN (edc_prelevements.plvconformitebacterio = 'N' OR  edc_prelevements.plvconformitechimique = 'N' 
                        OR  edc_prelevements.plvconformitereferencebact = 'N' OR  edc_prelevements.plvconformitereferencechim = 'N' )
            THEN 1 ELSE 0 END ) AS is_non_conforme,
        FROM
            edc_prelevements
        WHERE
          dateprel >= '{date_min}' 
    ),

    JOINTURE AS (
        SELECT
          RESULTATS.libmajparametre AS substance,
          RESULTATS.cat_polluant AS cat_polluant,
          RESULTATS.referenceprel AS referenceprel,
          PRELEVEMENTS.is_non_conforme AS is_non_conforme,
        FROM  
            RESULTATS  
        LEFT JOIN 
            PRELEVEMENTS
        ON 
          RESULTATS.referenceprel = PRELEVEMENTS.referenceprel
    )
  
    SELECT
      cat_polluant ,
      COUNT(*) AS nb_prel_tot,
      SUM(CASE WHEN is_non_conforme =1 THEN 1 ELSE 0 END ) AS nb_prel_non_conformes,
      ROUND(SUM(CASE WHEN is_non_conforme =1THEN 1 ELSE 0 END  )/ COUNT(*)  * 100,2) AS percent_prel_non_conformes_vs_all,
    FROM 
        JOINTURE
    GROUP BY 
        cat_polluant 
"""

con.sql(query_2024_count_conformity_cat).show()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

┌──────────────────────┬─────────────┬───────────────────────┬───────────────────────────────────┐
│     cat_polluant     │ nb_prel_tot │ nb_prel_non_conformes │ percent_prel_non_conformes_vs_all │
│       varchar        │    int64    │        int128         │              double               │
├──────────────────────┼─────────────┼───────────────────────┼───────────────────────────────────┤
│ hydrocarbures        │      362413 │                 28784 │                              7.94 │
│ pesticides           │     3046621 │                249168 │                              8.18 │
│ nitrates et nitrites │     1303547 │                 73272 │                              5.62 │
│ métaux lourds        │      481275 │                 30544 │                              6.35 │
│ phtalates            │        1426 │                    24 │                              1.68 │
│ other                │    58926728 │               4052777 │                              6.88 │
│ PFAS                 │       42488 │                  5376 │                             12.65 │
└──────────────────────┴─────────────┴───────────────────────┴───────────────────────────────────┘

##### CAS B

In [24]:
# [OPTIONAL]

query_check_refqual = """ 
SELECT 
  (CASE
    WHEN
        (LOWER(libmajparametre) LIKE '%azine%' OR
        LOWER(libmajparametre) LIKE '%phos%' OR
        LOWER(libmajparametre) LIKE '%triazine%' OR
        LOWER(libmajparametre) LIKE '%glyphosate%' OR
        LOWER(libmajparametre) LIKE '%atrazine%' OR
        LOWER(libmajparametre) LIKE '%metolachlor%') THEN 'pesticides'
    WHEN
        (LOWER(libmajparametre) LIKE '%nitrate%' OR
        LOWER(libmajparametre) LIKE '%nitrite%') THEN 'nitrates et nitrites'
    WHEN
        (LOWER(libmajparametre) LIKE '%fluoro%' OR
        LOWER(libmajparametre) LIKE '%perfluoro%' OR
        LOWER(libmajparametre) LIKE '%pfoa%' OR
        LOWER(libmajparametre) LIKE '%pfos%') THEN 'PFAS'
    WHEN
        (LOWER(libmajparametre) LIKE '%phtalate%' OR
        LOWER(libmajparametre) LIKE '%dehp%' OR
        LOWER(libmajparametre) LIKE '%bbp%' OR
        LOWER(libmajparametre) LIKE '%dbp%') THEN 'phtalates'
    WHEN
        libmajparametre = 'chlorure de vinyle' THEN 'chlorure de vinyle'
    WHEN
        (LOWER(libmajparametre) LIKE '%benzène%' OR
        LOWER(libmajparametre) LIKE '%toluène%' OR
        LOWER(libmajparametre) LIKE '%naphtalène%' OR
        LOWER(libmajparametre) LIKE '%xylène%') THEN 'hydrocarbures'
    WHEN
        (LOWER(libmajparametre) LIKE '%mercure%' OR
        LOWER(libmajparametre) LIKE '%plomb%' OR
        LOWER(libmajparametre) LIKE '%arsenic%' OR
        LOWER(libmajparametre) LIKE '%cadmium%' OR
        LOWER(libmajparametre) LIKE '%nickel%' OR
        LOWER(libmajparametre) LIKE '%chrome%') THEN 'métaux lourds'
    ELSE 'other'
  END ) AS cat_polluant,
  refqual
FROM  
    edc_resultats 
GROUP BY
    cat_polluant, refqual
HAVING 
    cat_polluant != 'other'
"""

con.sql(query_check_refqual).show()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

┌──────────────────────┬─────────┐
│     cat_polluant     │ refqual │
│       varchar        │ varchar │
├──────────────────────┼─────────┤
│ hydrocarbures        │ NULL    │
│ nitrates et nitrites │ NULL    │
│ métaux lourds        │ NULL    │
│ PFAS                 │ NULL    │
│ phtalates            │ NULL    │
│ pesticides           │ NULL    │
└──────────────────────┴─────────┘

Il n'y a pas de refqual pour les polluants<br>
Prenons 0.1 comme référence

In [25]:
# [TO RUN]

query_polluant_casB = """ 
WITH 
RESULATS AS (
    SELECT
      referenceprel,
      libmajparametre,
      (CASE
        WHEN
            (LOWER(libmajparametre) LIKE '%azine%' OR
            LOWER(libmajparametre) LIKE '%phos%' OR
            LOWER(libmajparametre) LIKE '%triazine%' OR
            LOWER(libmajparametre) LIKE '%glyphosate%' OR
            LOWER(libmajparametre) LIKE '%atrazine%' OR
            LOWER(libmajparametre) LIKE '%metolachlor%') THEN 'pesticides'
        WHEN
            (LOWER(libmajparametre) LIKE '%nitrate%' OR
            LOWER(libmajparametre) LIKE '%nitrite%') THEN 'nitrates et nitrites'
        WHEN
            (LOWER(libmajparametre) LIKE '%fluoro%' OR
            LOWER(libmajparametre) LIKE '%perfluoro%' OR
            LOWER(libmajparametre) LIKE '%pfoa%' OR
            LOWER(libmajparametre) LIKE '%pfos%') THEN 'PFAS'
        WHEN
            (LOWER(libmajparametre) LIKE '%phtalate%' OR
            LOWER(libmajparametre) LIKE '%dehp%' OR
            LOWER(libmajparametre) LIKE '%bbp%' OR
            LOWER(libmajparametre) LIKE '%dbp%') THEN 'phtalates'
        WHEN
            libmajparametre = 'chlorure de vinyle' THEN 'chlorure de vinyle'
        WHEN
            (LOWER(libmajparametre) LIKE '%benzène%' OR
            LOWER(libmajparametre) LIKE '%toluène%' OR
            LOWER(libmajparametre) LIKE '%naphtalène%' OR
            LOWER(libmajparametre) LIKE '%xylène%') THEN 'hydrocarbures'
        WHEN
            (LOWER(libmajparametre) LIKE '%mercure%' OR
            LOWER(libmajparametre) LIKE '%plomb%' OR
            LOWER(libmajparametre) LIKE '%arsenic%' OR
            LOWER(libmajparametre) LIKE '%cadmium%' OR
            LOWER(libmajparametre) LIKE '%nickel%' OR
            LOWER(libmajparametre) LIKE '%chrome%') THEN 'métaux lourds'
        ELSE 'other'
      END ) AS cat_polluant,
      (CASE WHEN valtraduite >= 0.1 THEN 1 ELSE 0 END) AS is_non_conforme
    FROM  
        edc_resultats 
    )
    
    SELECT
      cat_polluant ,
      COUNT(*) AS nb_test_tot,
      SUM(CASE WHEN is_non_conforme =1 THEN 1 ELSE 0 END ) AS nb_prel_non_conformes,
      ROUND(SUM(CASE WHEN is_non_conforme =1THEN 1 ELSE 0 END  )/ COUNT(*)  * 100,2) AS percent_prel_non_conformes_vs_all,
    FROM 
        RESULATS
    GROUP BY 
        cat_polluant 
"""

con.sql(query_polluant_casB).show()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

┌──────────────────────┬─────────────┬───────────────────────┬───────────────────────────────────┐
│     cat_polluant     │ nb_test_tot │ nb_prel_non_conformes │ percent_prel_non_conformes_vs_all │
│       varchar        │    int64    │        int128         │              double               │
├──────────────────────┼─────────────┼───────────────────────┼───────────────────────────────────┤
│ hydrocarbures        │      362413 │                   524 │                              0.14 │
│ pesticides           │     3046621 │                 27423 │                               0.9 │
│ métaux lourds        │      481275 │                 95482 │                             19.84 │
│ nitrates et nitrites │     1303547 │                738982 │                             56.69 │
│ phtalates            │        1426 │                    55 │                              3.86 │
│ other                │    58926728 │              12406245 │                             21.05 │
│ PFAS                 │       42488 │                    64 │                              0.15 │
└──────────────────────┴─────────────┴───────────────────────┴───────────────────────────────────┘